# Generated by Django 4.0.3 on 2022-03-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_import', models.FileField(upload_to='temp')),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.CharField(max_length=128, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='students.classroom', verbose_name='所属班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=32, verbose_name='学生名字'),
        ),
    ]
